name: Build Spes Kernel with KernelSU

on:
  workflow_dispatch:  # allows manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison flex git clang lld llvm zip make python3 ccache curl wget

      - name: Clone KernelSU
        run: |
          git clone https://github.com/tiann/KernelSU.git kernel/KernelSU --depth=1

      - name: Set up Proton Clang
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git clang

      - name: Setup Build Environment
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export PATH=$PWD/clang/bin:$PATH
          export KBUILD_BUILD_USER=github
          export KBUILD_BUILD_HOST=actions
          spes-perf_deconfig: Rename local version to Reze

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export PATH=$PWD/clang/bin:$PATH
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          make O=out ARCH=arm64 spes_defconfig

      - name: Upload Compiled Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Spes-Kernel
          path: out/arch/arm64/boot/Image.gz-dtb
